// export const samplePages = [
//   {
//     label: 1,
//     isClicked: false,
//   },
//   {
//     label: 2,
//     isClicked: false,
//   },

//   {
//     label: 3,
//     isClicked: false,
//   },
//   {
//     label: 4,
//     isClicked: false,
//   },
//   {
//     label: 5,
//     isClicked: false,
//   },
// ];



// export const sampleData = [
//   {
//     id: '1',
//     name: 'Aaron Miles',
//     email: 'aaron@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '2',
//     name: 'Aishwarya Naik',
//     email: 'aishwarya@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '3',
//     name: 'Arvind Kumar',
//     email: 'arvind@mailinator.com',
//     role: 'admin',
//   },
//   {
//     id: '4',
//     name: 'Brenda Smith',
//     email: 'brenda@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '5',
//     name: 'Carlos Rodriguez',
//     email: 'carlos@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '6',
//     name: 'Catherine White',
//     email: 'catherine@mailinator.com',
//     role: 'admin',
//   },
//   {
//     id: '7',
//     name: 'David Lee',
//     email: 'david@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '8',
//     name: 'Diana Johnson',
//     email: 'diana@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '9',
//     name: 'Daniel Brown',
//     email: 'daniel@mailinator.com',
//     role: 'admin',
//   },
//   {
//     id: '10',
//     name: 'Emily Davis',
//     email: 'emily@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '11',
//     name: 'Elijah Taylor',
//     email: 'elijah@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '12',
//     name: 'Eva Martinez',
//     email: 'eva@mailinator.com',
//     role: 'admin',
//   },
//   {
//     id: '13',
//     name: 'Frank Miller',
//     email: 'frank@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '14',
//     name: 'Fiona Adams',
//     email: 'fiona@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '15',
//     name: 'George Wilson',
//     email: 'george@mailinator.com',
//     role: 'admin',
//   },
//   {
//     id: '16',
//     name: 'Grace Turner',
//     email: 'grace@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '17',
//     name: 'Gary Brown',
//     email: 'gary@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '18',
//     name: 'Hannah Taylor',
//     email: 'hannah@mailinator.com',
//     role: 'admin',
//   },
//   {
//     id: '19',
//     name: 'Henry Adams',
//     email: 'henry@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '20',
//     name: 'Ivy Davis',
//     email: 'ivy@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '21',
//     name: 'Isaac Johnson',
//     email: 'isaac@mailinator.com',
//     role: 'admin',
//   },
//   {
//     id: '22',
//     name: 'Jessica Smith',
//     email: 'jessica@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '23',
//     name: 'James Lee',
//     email: 'james@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '24',
//     name: 'Julia Brown',
//     email: 'julia@mailinator.com',
//     role: 'admin',
//   },
//   {
//     id: '25',
//     name: 'John Davis',
//     email: 'john@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '26',
//     name: 'Jennifer White',
//     email: 'jennifer@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '27',
//     name: 'Kevin Taylor',
//     email: 'kevin@mailinator.com',
//     role: 'admin',
//   },
//   {
//     id: '28',
//     name: 'Karen Adams',
//     email: 'karen@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '29',
//     name: 'Kyle Brown',
//     email: 'kyle@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '30',
//     name: 'Laura Smith',
//     email: 'laura@mailinator.com',
//     role: 'admin',
//   },
//   {
//     id: '31',
//     name: 'Luke Davis',
//     email: 'luke@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '32',
//     name: 'Lily White',
//     email: 'lily@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '33',
//     name: 'Mark Johnson',
//     email: 'mark@mailinator.com',
//     role: 'admin',
//   },
//   {
//     id: '34',
//     name: 'Melissa Taylor',
//     email: 'melissa@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '35',
//     name: 'Michael Brown',
//     email: 'michael@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '36',
//     name: 'Natalie Adams',
//     email: 'natalie@mailinator.com',
//     role: 'admin',
//   },
//   {
//     id: '37',
//     name: 'Nathan Davis',
//     email: 'nathan@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '38',
//     name: 'Olivia White',
//     email: 'olivia@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '39',
//     name: 'Oscar Taylor',
//     email: 'oscar@mailinator.com',
//     role: 'admin',
//   },
//   {
//     id: '40',
//     name: 'Penelope Smith',
//     email: 'penelope@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '41',
//     name: 'Paula Brown',
//     email: 'paula@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '42',
//     name: 'Quincy Adams',
//     email: 'quincy@mailinator.com',
//     role: 'admin',
//   },
//   {
//     id: '43',
//     name: 'Quinn Davis',
//     email: 'quinn@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '44',
//     name: 'Rebecca White',
//     email: 'rebecca@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '45',
//     name: 'Richard Johnson',
//     email: 'richard@mailinator.com',
//     role: 'admin',
//   },
//   {
//     id: '46',
//     name: 'Rachel Brown',
//     email: 'rachel@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '47',
//     name: 'Samuel Davis',
//     email: 'samuel@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '48',
//     name: 'Samantha White',
//     email: 'samantha@mailinator.com',
//     role: 'admin',
//   },
//   {
//     id: '49',
//     name: 'Thomas Adams',
//     email: 'thomas@mailinator.com',
//     role: 'member',
//   },
//   {
//     id: '50',
//     name: 'Tanya Taylor',
//     email: 'tanya@mailinator.com',
//     role: 'member',
//   },
// ];
